# redirect default route to login form
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: security_connexion
        permanent: true

#route logout (used in security.yaml)
security_logout:
    path: /register/logout.html
